from pathlib import Path
from html import escape
from device_markup import device_markup, PHONE_IMAGES
import re
root=Path(__file__).parent/'dist'
home=(root/'index.html').read_text()
figma='https://www.figma.com/design/ZvkPFit2LyQPYbr1n8xsj8/Alexander-Grenkov.-Product-Designer--Copy-?node-id='
cases=[
 {'slug': 'atom', 'name': 'ATOM · In-car AI assistant', 'title': 'Your car.<br>One AI assistant.', 'category': 'AI ASSISTANT × VEHICLE CONTROL', 'role': 'Lead Product Designer', 'period': 'Jan 2023 — Jan 2026', 'focus': 'AI assistant · HMI · Voice & sound UX', 'node': '13888-19678', 'theme': 'atom', 'metric': 'AI', 'metric_label': 'Vehicle function control', 'intro': 'An in-car AI assistant for vehicle functions, with conversational flows, contextual quick actions and clear sound feedback. Part of a wider ATOM cockpit experience spanning voice, touch and physical controls.', 'challenge': 'Make in-car communication intuitive and consistent, from activating the assistant to completing a conversational flow. Define how the assistant behaves across key use cases, with clear navigation, contextual actions and feedback.', 'solution': 'Led UX for the assistant’s interaction logic, prompts, intents and conversational flows. Defined tone of voice, navigation principles and behavior across key in-car scenarios, and designed audio feedback for system states, alerts, confirmations and contextual interactions.', 'details': [('Activation and listening', 'Designed the assistant experience from the initial button press and listening state through conversational interaction.'), ('Intents and quick actions', 'Structured prompts, intents and conversational flows alongside contextual suggestions for frequent vehicle actions.'), ('Consistent assistant behavior', 'Defined tone of voice and navigation principles to create a coherent experience across in-car use cases.'), ('Audio feedback', 'Designed sound patterns for system states, alerts and confirmations, and developed the assistant’s audio identity.')], 'outcome': 'Established a structured foundation for voice and sound interaction, making communication clearer and more consistent from a button press to a complete conversational flow.', 'related_title': 'Sound across the vehicle.', 'related_body': 'Developed sound identity principles and led AVAS design for the vehicle ecosystem. Audio feedback patterns cover system states, alerts, confirmations and contextual interactions.', 'images': [('atom-assistant-ui.png', 'ATOM assistant interaction flow'), ('atom-e-mirror.png', 'e-Mirror interaction design'), ('atom-widget-panel.png', 'Smart Widget Panel interaction design')], 'gallery_template': 'atom-details.html'},
 dict(slug='beeline-b2b',name='Beeline · B2B portal',title='From catalog<br>to conversion.',category='B2B × COMMERCE',role='Lead Product Designer',focus='Storefront · Navigation · Design systems',node='11869-87697',theme='beeline',metric='+20%',metric_label='Online sales',intro='Transforming a B2B catalog into a digital storefront that helps customers find, compare and buy business services.',challenge='Increase online sales through the Beeline B2B portal. The product catalog needed to become a clearer path to choosing and purchasing a service.',solution='Restructured the catalog as a product store, simplified navigation and decision-making, clarified pricing, and strengthened cross-sell and upsell flows.',details=[('A clearer storefront','Simplified navigation so customers could move through the business service offering.'),('Better purchase decisions','Introduced a clearer pricing structure and improved the paths to related products and upgrades.')],outcome='The redesigned storefront achieved a 20% increase in online sales.',images=[('beeline.png','Beeline business storefront — service navigation and product categories.'),('beeline-detail.png','Additional interface detail from the B2B portal.')]),
 dict(slug='national-parking',name='National Parking App',title='Less friction.<br>More movement.',category='MOBILITY × MOBILE',role='Lead Product Designer',focus='Mobile UX · Design system',node='12368-10525',theme='parking',metric='−10%',metric_label='Support requests',intro='Improving the parking experience through clearer navigation, simpler checkout and a consistent design system.',challenge='Improve the user experience and increase product monetization in the National Parking App.',solution='Designed parking applications for Android and iOS from research through visual design. Developed a design system and optimized key user flows, including navigation, checkout, pricing and upsell logic.',details=[('A consistent foundation','Created a design system to support a coherent mobile experience.'),('Simpler key journeys','Refined navigation and checkout alongside the product’s pricing and upsell flows.')],outcome='Reduced support requests by 10% and increased average order value.',images=[('parking.png','Vehicle setup in the National Parking App.'),('parking-detail.png','Additional mobile interface from the parking experience.')],phone=True),
 dict(slug='beeline-marketing',name='Beeline · Marketing platform',title='Connections<br>that grow.',category='B2B × MARKETING',role='Lead Product Designer',focus='Campaigns · Audience management',node='11880-117898',theme='marketing',metric='Connected',metric_label='Marketing ecosystem',intro='An ecosystem of tools for customer acquisition, audience engagement and retention.',challenge='Design a platform for customer acquisition and audience engagement, bringing the related marketing tools into one ecosystem.',solution='Designed campaign management, audience segmentation, analytics and user interaction flows as parts of a connected marketing platform. The wider Beeline role included ownership of design systems, UX research and collaboration with external studios.',details=[('Campaigns and audiences','Designed tools for managing campaigns and segmenting audiences.'),('A connected workflow','Brought analytics and user interaction flows into the wider marketing ecosystem.')],outcome='Launched a platform for customer acquisition, retention and audience management.',images=[('marketing.png','Campaign display settings and scheduling controls.'),('marketing-detail.png','Additional interface from the marketing platform.')]),
 dict(slug='beeline-pricing',name='Beeline · Pricing plan builder',title='A clearer<br>choice.',category='TELECOM × CONVERSION',role='Lead Product Designer',focus='Pricing · Comparison · Decision-making',node='10491-39981',theme='pricing',metric='+5%',metric_label='Plan sales',intro='Helping customers understand the offer and choose a plan through clearer pricing and comparison.',challenge='Increase tariff plan sales by reducing the complexity of choosing between available offers.',solution='Optimized the pricing structure and presentation. Simplified comparison tables, introduced visual hierarchy and recommended plans, and reduced decision complexity.',details=[('Easier comparison','Restructured the presentation of plans to make comparison clearer.'),('More focused decisions','Used visual hierarchy and recommended plans to guide the selection process.')],outcome='Achieved a 5% increase in sales, improved conversion and reduced user decision time.',images=[('pricing.png','Beeline plan card with allowances, benefits and pricing.'),('pricing-detail.png','Additional interface from the pricing plan builder.')],phone=True),
 dict(slug='cargo-monitoring',name='Cargo Transport Monitoring',title='Complex operations.<br>Clear decisions.',category='LOGISTICS × OPERATIONS',role='Lead Product Designer',focus='Operational UX · Automation',node=None,theme='cargo',metric='+40%',metric_label='Process automation',intro='Redesigning operational workflows in a cargo transport monitoring system to reduce manual work.',challenge='Reduce manual operations and improve operational efficiency in cargo transport monitoring.',solution='Redesigned key user flows, removed friction points and increased the level of process automation.',details=[('Workflow simplification','Reworked key user flows to reduce friction in operational tasks.'),('Less manual work','Focused the redesign on increasing the automation of existing processes.')],outcome='Achieved a 40% increase in process automation.',images=[('cargo.png','Cargo monitoring interface with a violation record, vehicle details and measurement data.')]),
 dict(slug='sound-stream',name='Sound Stream',title='Find your next<br>great listen.',category='AUDIO × MOBILE EXPERIENCE',role='Lead Product Designer',focus='App redesign · UI-kit · Design system',node='13847-209',theme='sound-stream',metric='UI-kit',metric_label='Foundation for app and web',intro='A redesign concept for an audio app, connecting discovery, new episodes and a personal library through a consistent visual language.',challenge='Address the interface problems identified through research and develop an updated app concept based on iOS.',solution='Redesigned the core screens, defined typography and base colors, and established principles for content cards. The concept became a UI-kit that was later developed into a design system for the apps and web platform.',details=[('Listening journeys','Connected editorial recommendations, new episodes, catalog browsing and a personal library.'),('Reusable design foundations','Defined typography, color principles and core card types to support a consistent experience.')],outcome='The design concept and UI-kit provided the foundation for a design system spanning the apps and web platform.',images=[('sound-stream-home.png','Sound Stream home screen and recommendations.')],gallery_template='sound-stream-details.html')
]
# Use descriptive product headings instead of promotional slogans.
product_titles = {
 'atom': 'AUTOMOTIVE · AI ASSISTANT · DESIGN LEAD',
 'beeline-b2b': 'COMMERCE · DESIGN SYSTEMS',
 'national-parking': 'MOBILITY · PRODUCT DESIGN',
 'beeline-marketing': 'B2B · AUDIENCE ENGAGEMENT',
 'beeline-pricing': 'TELECOM · CONVERSION',
 'cargo-monitoring': 'LOGISTICS · PRODUCT DESIGN',
 'sound-stream': 'AUDIO · MOBILE EXPERIENCE · UI-KIT',
}
for case in cases:
 case['title'] = product_titles[case['slug']]
favicon=re.search(r'<link rel="icon"[^>]+>',home).group()
for index,c in enumerate(cases):
 prev=cases[(index-1)%len(cases)];nxt=cases[(index+1)%len(cases)]
 period_fact=f'<div><dt>PERIOD</dt><dd>{escape(c["period"])}</dd></div>' if c.get('period') else ''
 related=f'<section class="case-related section"><p class="eyebrow">RELATED AUTOMOTIVE WORK</p><h2>{escape(c["related_title"])}</h2><p>{escape(c["related_body"])}</p></section>' if c.get('related_title') else ''
 gallery=''
 if c['images']:
  figures=''
  for img,caption in c['images']:
   visual=device_markup(img,caption) if img in PHONE_IMAGES else f'<img src="/assets/{img}" alt="{escape(caption)}" loading="lazy">'
   device_class=' device-stage' if img in PHONE_IMAGES else ''
   figures+=f'<figure><a class="case-screen{device_class}" href="/assets/{img}" target="_blank" rel="noopener noreferrer" aria-label="View full-size interface: {escape(caption,quote=True)}">{visual}</a><figcaption>{escape(caption)} <a href="/assets/{img}" target="_blank" rel="noopener noreferrer">View full size ↗</a></figcaption></figure>'
  gallery=f'<section class="case-gallery section" id="screens"><div class="section-heading"><h2>The interface.</h2><span class="eyebrow">SELECTED SCREENS</span></div><div class="screens-grid {"phone-screens" if c.get("phone") else ""} {"single-screen" if len(c["images"])==1 else ""}">{figures}</div></section>'
 if c.get('phone'):
  phones=''.join(f'<a class="phone-stack-item" href="/assets/{img}" target="_blank" rel="noopener noreferrer" aria-label="View full-size interface: {escape(caption,quote=True)}">{device_markup(img,caption)}</a>' for img,caption in c['images'])
  captions=''.join(f'<p>{escape(caption)} <a href="/assets/{img}" target="_blank" rel="noopener noreferrer">View full size ↗</a></p>' for img,caption in c['images'])
  gallery=f'<section class="case-gallery section" id="screens"><div class="section-heading"><h2>The interface.</h2><span class="eyebrow">SELECTED SCREENS</span></div><figure class="phone-overlap"><div class="case-phone-stack">{phones}</div><figcaption class="stack-captions">{captions}</figcaption></figure></section>'
 if c.get('gallery_template'):
  gallery=(root.parent/'templates'/c['gallery_template']).read_text()
 extra_templates={'beeline-b2b':'b2b-details.html','national-parking':'parking-details.html','beeline-pricing':'pricing-details.html','beeline-marketing':'marketing-details.html'}
 if c['slug'] in extra_templates:
  gallery+=(root.parent/'templates'/extra_templates[c['slug']]).read_text()
 steps=''.join(f'<div class="case-detail"><h3>{escape(title)}</h3><p>{escape(body)}</p></div>' for i,(title,body) in enumerate(c['details']))
 figma_link=f'<a class="case-button" href="{figma+c["node"]}" target="_blank" rel="noopener noreferrer">View in Figma <span aria-hidden="true">↗</span></a>' if c['node'] else ''
 screens_link='<a href="#screens">Screens</a>' if c['images'] else ''
 body=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(c['name'])} — WOCNERG</title><meta name="description" content="{escape(c['intro'],quote=True)}"><meta name="theme-color" content="#181916">{favicon}<link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/case.css?v=20260923-one-column"><link rel="stylesheet" href="/devices.css?v=20260923-pair"><link rel="stylesheet" href="/themes.css?v=3"><script src="/themes.js?v=1"></script></head><body class="case-page case-{c['theme']}">
<a class="skip" href="#overview">Skip to case study</a>
<header class="header"><a href="/" class="brand" aria-label="Wocnerg home">wocnerg<span>®</span></a><nav aria-label="Main navigation"><a href="/#work">Selected work</a><a href="/#about">About</a><a class="contact-nav" href="https://t.me/wocnerg" target="_blank" rel="noopener noreferrer">Let’s talk ↗</a></nav></header>
<main><section class="case-hero case-hero-illustrated"><img class="case-hero-background" src="/assets/hero-{c['slug']}-generated.jpg" alt="" aria-hidden="true" fetchpriority="high" decoding="async"><div class="case-breadcrumb"><a href="/#work">← All projects</a></div><p class="eyebrow">{escape(c['category'])}</p><h1>{c['title']}</h1><div class="case-intro"><h2>{escape(c['name'])}</h2><p>{escape(c['intro'])}</p></div></section>
<div class="case-toolbar"><nav aria-label="On this page"><a href="#overview">Overview</a><a href="#solution">Approach</a>{screens_link}<a href="#outcome">Outcome</a></nav>{figma_link}</div>
<section class="case-overview section" id="overview"><aside class="case-facts"><dl>{period_fact}<div><dt>ROLE</dt><dd>{escape(c['role'])}</dd></div><div><dt>FOCUS</dt><dd>{escape(c['focus'])}</dd></div></dl></aside><div class="case-prose"><p class="eyebrow">THE CHALLENGE</p><h2>What needed to change.</h2><p>{escape(c['challenge'])}</p></div></section>
<section class="case-solution section" id="solution"><div class="case-prose"><p class="eyebrow">THE APPROACH</p><h2>From problem to product.</h2><p>{escape(c['solution'])}</p></div><div class="case-details">{steps}</div></section>
{gallery}
{related}
<section class="case-outcome section" id="outcome"><div><p class="eyebrow">THE OUTCOME</p><h2>{escape(c['metric'])}</h2><span>{escape(c['metric_label'])}</span></div><p>{escape(c['outcome'])}</p></section>
<nav class="case-pagination section" aria-label="More projects"><a href="/work/{prev['slug']}/"><span class="eyebrow">← PREVIOUS PROJECT</span><strong>{escape(prev['name'])}</strong></a><a href="/work/{nxt['slug']}/"><span class="eyebrow">NEXT PROJECT →</span><strong>{escape(nxt['name'])}</strong></a></nav>
</main><footer><a href="/" class="brand">wocnerg<span>®</span></a><span>© 2026 ALEKSANDR GRENKOV</span><a href="/#work">All projects ↑</a></footer></body></html>'''
 target=root/'work'/c['slug']/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(body)
print(f'Created {len(cases)} case pages.')
